<h2>Playlist songs</h2>
<?php 
    if(count($this->songs) > 0):
        echo '<table class="dates" cellpadding="0" cellspacing="0" border="0">
        <tr class="thead">
            <td>Code</td>
            <td>Title</td>
            <td></td>
        </tr>';
        foreach($this->songs as $song):
           echo '<tr>
                    <td>' . $song['songId'] . '</td>
                    <td><span class="songTitle">' . $song['songTitle'] . '</span><span> ( ' . $song['size'] . ' ) </span></td>
                    <td><span class="playme" style="width:100px;" data-url="' . $this->baseUrl() .'/music/' . $song['url'] . '"><img src="' . $this->baseUrl() . '/css/play.png"/></span></td>
                </tr>';
        endforeach;
    echo '</table>';
    else:echo "There are no songs for this artist";
    endif;
?>