<h2>About</h2>
<h4>Music portal is a service for downloading songs via SMS.</h4>
<h2>Download songs</h2>
<h4>This web site is provided sorting songs by category, and search.</h4>
<h4>When sorting and searching gets a list of songs with their codes.</h4>
<h2>Info by SMS</h2>
<h4>"INFO" send to +381645854399</h4>
<h2>Search by SMS</h2>
<h4>"SEARCH*SONG_TITLE" send to +381645854399</h4>
<h4>Example: "SEARCH*Wake Me Up"</h4>
<h2>Download via SMS</h2>
<h4>"SONG*CODE" send to +381645854399</h4>
<h4>Example: "SONG*30"</h4>
<h4><strong>Codes you get via search or you can find them on the site.</strong></h4>
<h2>Wishes by SMS</h2>
<h4>"WISH*USERNAME*PASSWORD*TEXT" send to +381645854399</h4>
<h4>WISH*zarko*stanisic88*Turn Me On</h4>
<h4><strong>To send wishes must be registered</strong></h4>