<h2>Add a artist</h2>
<?php 
    echo $this->add_artist;
?>
<hr/>
<div class="table-border tableborder">
<?php
    if(count($this->artists) > 0):
?>
<table class="dates" cellpadding="0" cellspacing="0" border="0">
        <tr class="thead">
            <td>Id</td>
            <td>Artist name</td>
            <td>Status</td>
            <td></td>
        </tr>
<?php
        foreach($this->artists as $artist):
            echo "<tr>";
            echo "<td>" . $artist['artistId'] . "</td>";
            echo "<td>" . $artist['artistName'] . "</td>";
            echo "<td>";
            if($artist['status'] == 1){
                echo "Allow";
            }else{
                echo "Block";
            }
            echo "</td>";
            echo "<td>";
                    if($artist['status'] == 1){
                        echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'artists', 'block' => $artist['artistId']), null, true) . "' class='block'></a>";
                    }else{
                        echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'artists', 'allow' => $artist['artistId']), null, true) . "' class='allow'></a>";
                    }
                    echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'editartist', 'id' => $artist['artistId']), null, true) . "' class='edit'></a>
                  </td>";
            echo "</tr>";
        endforeach;
?>
</table>
<?php
    endif;
?>
</div>