<h2>Users</h2>
<hr/>
<div class="table-border tableborder">
<?php
    if(count($this->users) > 0):
?>
<table class="dates" cellpadding="0" cellspacing="0" border="0">
        <tr class="thead">
            <td>Id</td>
            <td>Username</td>
            <td>Status</td>
            <td>Role</td>
            <td></td>
        </tr>
<?php
        foreach($this->users as $user):
            echo "<tr>";
            echo "<td>" . $user['userId'] . "</td>";
            echo "<td>" . $user['username'] . "</td>";
            echo "<td>";
            if($user['status'] == 1){
                echo "Allow";
            }else{
                echo "Block";
            }
            echo "</td>";
            echo "<td>" . $user['roleTitle'] . "</td>";
            echo "<td>";
                    if($user['status'] == 1){
                        echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'users', 'block' => $user['userId']), null, true) . "' class='block'></a>";
                    }else{
                        echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'users', 'allow' => $user['userId']), null, true) . "' class='allow'></a>";
                    }
                    echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'edituser', 'id' => $user['userId']), null, true) . "' class='edit'></a>";
                  echo "</td>";
            echo "</tr>";
        endforeach;
?>
</table>
<?php
    endif;
?>
</div>