<h2>Wishes</h2>
<?php 
    if(count($this->wishes) > 0):
        echo '<table class="dates" cellpadding="0" cellspacing="0" border="0">
        <tr class="thead">
            <td>Id</td>
            <td>User</td>
            <td>Wish</td>
            <td>Filled</td>
            <td></td>
        </tr>';
        foreach($this->wishes as $wish):
           echo '<tr>
                    <td>' . $wish['wishId'] . '</td>
                    <td><span class="songTitle">' . $wish['username'] . '</span></td>
                    <td>' . $wish['wish'] . '</td>
                    <td>';
                    if($wish['wishStatus'] == '1'){
                        echo "Yes";
                    }else{
                        echo "No";
                    }
                    echo '</td>';
                    echo '<td>';
                        if($wish['wishStatus'] == 1){
                            echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'wishes', 'block' => $wish['wishId']), null, true) . "' class='block'></a>";
                        }else{
                            echo "<a href='" . $this->url(array('controller' => 'Administration', 'action' => 'wishes', 'allow' => $wish['wishId']), null, true) . "' class='allow'></a>";
                        }
                    echo '</td>';
                echo '</tr>';
        endforeach;
    echo '</table>';
    else:echo "There are no wishes";
    endif;
?>